id: P6685086B
initial_creation_type: input
source_metadata:
  title: Śavari
  language: bo
  description: 'Texts by and about the mahāsiddha Śavari/Śabari (ri khrod zhabs),
    the Hunter:'
  volume:
    dd3cfa2b50774845b0c3e51aa38696da:
      title: A Guru Yoga of Śavari
      parent: Guru Yoga
created_at: '2022-03-01T02:23:59.927599'
last_modified_at: '2022-03-01T02:23:59.927602'
statistics:
  total_words: 1094
  total_non_words: 187
quality:
  non_words_ratio: 0.17
